/**
 * CourseNameDaoJDBC.java
 *
 *  @author Daniel Bispo <danielvbispo@outlook.com>
 *  Created on 27 de jan de 2019
 *  GNU License
 *
 */
package model.dao.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import db.DB;
import db.DbException;
import model.dao.CrudDAO;
import model.entities.Effectivity;

/**
 * Implementation of CrudDAO for CourseNameDaoJDBC entity. It uses JDBC
 * connection only.
 */
public class EffectivityDaoJDBC implements CrudDAO<Effectivity> {

	private Connection conn;

	public EffectivityDaoJDBC(Connection conn) {
		this.conn = conn;
	}

	@Override
	// A new Effectivity object has to be created before. Then use that as the
	// parameter
	// for this method
	public void insert(Effectivity obj) {

		String sql = "INSERT INTO effectivity (effec_info, create_date, update_date, user_loggin) VALUES (?, ?, ?, ?)";

		PreparedStatement pstmt = null;

		try {

			/*
			 * Statement.RETURN_GENERATED_KEYS is needed as second parameter to get the key
			 * generated by the database, since it will be used to update the object's id
			 */
			pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
			pstmt.setString(1, obj.getEffecInfo());
			pstmt.setString(2, new Date().toString()); // Set to today always
			pstmt.setString(3, obj.getUpdateDate());
			pstmt.setString(4, obj.getUserLoggin());

			// Get the amount of the inserted row
			int insRows = pstmt.executeUpdate();

			if (insRows > 0) {
				ResultSet rs = pstmt.getGeneratedKeys();

				if (rs.next()) {
					obj.setId(rs.getInt(1)); // Set a new object Id according to database
				}
				DB.closeResultSet(rs);
			} else {
				throw new DbException("Unespected error when trying to set a new id for the effectitivy!");
			}

		} catch (SQLException e) {
			throw new DbException(e.getMessage());
		} finally {
			DB.closeStatement(pstmt);
		}
	}

	@Override
	// An new Effectivity object has to be created before. Then use that as the
	// parameter
	// for this method
	public void upDate(Effectivity obj) {

		String sql = "UPDATE effectivity SET effec_info=?, create_date=?, update_date=?, user_loggin=? WHERE id=?";

		PreparedStatement pstmt = null;

		try {

			pstmt = conn.prepareStatement(sql);
			pstmt.setString(1, obj.getEffecInfo());
			pstmt.setString(2, obj.getCreateDate());
			pstmt.setString(3, new Date().toString()); // Set to today always
			pstmt.setString(4, obj.getUserLoggin());
			pstmt.setInt(5, obj.getId());

			pstmt.executeUpdate();

		} catch (SQLException e) {
			throw new DbException(e.getMessage());
		} finally {
			DB.closeStatement(pstmt);
		}
	}

	@Override
	public void deleteById(int id) {

		String sql = "DELETE FROM effectivity WHERE id=?";

		PreparedStatement pstmt = null;

		try {

			pstmt = conn.prepareStatement(sql);
			pstmt.setInt(1, id);
			pstmt.executeUpdate();

		} catch (SQLException e) {
			throw new DbException(e.getMessage());
		} finally {
			DB.closeStatement(pstmt);
		}
	}

	@Override
	public Effectivity findById(int id) {

		String sql = "SELECT * FROM effectivity WHERE id=?";

		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {
			pstmt = conn.prepareStatement(sql);
			pstmt.setInt(1, id);

			rs = pstmt.executeQuery();

			if (rs.next()) {
				return createEffectivityObj(rs);
			}

			return null;

		} catch (SQLException e) {
			throw new DbException(e.getMessage());
		} finally {
			DB.closeStatement(pstmt);
			DB.closeResultSet(rs);
		}
	}

	@Override
	public List<Effectivity> findAll() {

		// A list which contains all Effectivity elements read from database
		List<Effectivity> effectivityList = new ArrayList<>();

		String sql = "SELECT * FROM effectivity ORDER BY effec_info";

		PreparedStatement pstmt = null;
		ResultSet rs = null;

		try {

			pstmt = conn.prepareStatement(sql);
			rs = pstmt.executeQuery();

			while (rs.next()) {

				effectivityList.add(createEffectivityObj(rs));
			}

			return effectivityList;

		} catch (SQLException e) {
			throw new DbException(e.getMessage());
		} finally {
			DB.closeStatement(pstmt);
			DB.closeResultSet(rs);
		}
	}

	// Instantiate an Effectivity object used by findAll()
	private Effectivity createEffectivityObj(ResultSet rs) throws SQLException {

		Effectivity effectivity = new Effectivity();

		effectivity.setId(rs.getInt("id"));
		effectivity.setEffecInfo(rs.getString("effec_info"));
		effectivity.setCreateDate(rs.getString("create_date"));
		effectivity.setUpdateDate(rs.getString("update_date"));
		effectivity.setUserLoggin(rs.getString("user_loggin"));

		return effectivity;
	}
}
